version: "3.1"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_PASSWORD: sabino
      POSTGRES_USER: postgres
      POSTGRES_DB: sabino-ts
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  timescaledb-data:
